# Generated by Django 4.1.5 on 2023-04-24 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Marka')),
                ('slug', models.SlugField(blank=True, verbose_name='Marka Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=50, verbose_name='Renkler Türkçe')),
                ('title2', models.CharField(max_length=50, verbose_name='Renkler İngilizce')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Ürün Başlığı')),
                ('text', models.TextField(verbose_name='İçerik')),
                ('price', models.FloatField(verbose_name='Ürün fiyatı')),
                ('total_rating', models.FloatField(verbose_name='Ürün Puanı')),
                ('image', models.ImageField(max_length=250, upload_to='product', verbose_name='Ürün Resmi')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProduct.brand', verbose_name='Marka')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kulanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Beden')),
            ],
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok', models.IntegerField(verbose_name='Stok Sayısı')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProduct.color', verbose_name='Renk')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProduct.product', verbose_name='Ürün')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProduct.size', verbose_name='Beden')),
            ],
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=250, upload_to='product', verbose_name='Ürün Resmi')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProduct.color', verbose_name='Renk')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProduct.product', verbose_name='Ürün')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('text', models.TextField(verbose_name='Yorum')),
                ('rating', models.IntegerField(verbose_name='Yorum Puanı')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProduct.product', verbose_name='Ürün')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kulanıcı')),
            ],
        ),
    ]
