# Generated by Django 4.1.5 on 2023-04-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Title Slug'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=5, verbose_name='Yorum Puanı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, verbose_name='Ürün fiyatı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_rating',
            field=models.FloatField(default=0, verbose_name='Ürün Puanı'),
        ),
        migrations.AlterField(
            model_name='stok',
            name='stok',
            field=models.IntegerField(default=0, verbose_name='Stok Sayısı'),
        ),
    ]
