# Generated by Django 4.1.5 on 2023-04-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0002_product_slug_alter_comment_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(to='appProduct.color', verbose_name='Renkler'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(to='appProduct.size', verbose_name='Bedenler'),
        ),
    ]
