# Generated by Django 4.1.5 on 2023-05-05 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appProduct', '0004_remove_comment_title_comment_date_now'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanity', models.IntegerField(verbose_name='Adet')),
                ('all_price', models.FloatField(verbose_name='Toplam Ürün Fiyatı')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProduct.color', verbose_name='Renk')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProduct.product', verbose_name='Ürün')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProduct.size', verbose_name='Beden')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
