# Generated by Django 4.1.5 on 2023-05-08 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0005_shoping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoping',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appProduct.imageproduct', verbose_name='Ürün Fotoğrafı'),
        ),
    ]
