# Generated by Django 4.1.5 on 2023-05-08 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0006_shoping_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoping',
            old_name='image',
            new_name='imageproduct',
        ),
    ]
